#!/bin/bash -e

# Map environment variables to entries in logstash.yml.
# Note that this will mutate logstash.yml in place if any such settings are found.
# This may be undesirable, especially if logstash.yml is bind-mounted from the
# host system.
env2yaml /usr/share/logstash/config/logstash.yml

sed -i "s|{{API_ENDPOINT}}|${API_ENDPOINT:-''}|g" /usr/share/logstash/pipeline/logstash.conf
sed -i "s|{{API_KEY}}|${API_KEY:-''}|g" /usr/share/logstash/pipeline/logstash.conf
sed -i "s|{{API_SECRET}}|${API_SECRET:-''}|g" /usr/share/logstash/pipeline/logstash.conf
sed -i "s|{{LOG_FILE}}|${LOG_FILE:-'app.log'}|g" /usr/share/logstash/pipeline/logstash.conf
sed -i "s|{{LOG_SINCEDB_INTERVAL}}|${LOG_SINCEDB_INTERVAL:-5}|g" /usr/share/logstash/pipeline/logstash.conf

if [[ ${1:0:1} == '-' ]]; then
  exec logstash $@
else
  exec $@
fi
